[metadata]
name = pixelface
version = 0.0.1
author = Ankur Debnath
author_email = jordanh0pe@pm.me
description = Pixel Face - Face Reconstruction from Blurred CCTV images and videos
description-file = README.md
url = package_url
keywords = opensource, python, machine-learning

[options]
python_required = >=3.10.0
package_dir =
    = src